### PR TITLE
Fixing bug in EnumField

### PR DESCRIPTION
**Pull request by pykong**
**WIP** - Wait before tests are in place.

Making PR. 
With next merge basic tests need to be in place.

### CODE REVIEW

**Comment by ghost** [comment]
I added basic Docs for `EnumField` on Readme, please Pull from Master to Sync.

I was checking the EnumField code and I dont understand where the Enum itself is getting persisted, 
because it cant be persisted only on memory, it will get lost on program restart (???).

:smiley_cat:

**Comment by prurph** [comment]
I'm getting `'EnumField' object has no attribute 'model_class'` when trying to select from a (Sqlite) database with an enum field. It arises from [here](https://github.com/juancarlospaco/peewee-extra-fields/blob/master/peewee_extra_fields/__init__.py#L1033). It doesn't look like this will address it though, so it's a separate issue I think.

**Comment by juancarlospaco** [comment]
Main Support target is PostgreSQL.
Because some stuff is not really doable with other databases.
:sweat_smile:

**Comment by juancarlospaco** [comment]
Hows the work progressing @pykong :grey_question:

**Comment by pykong** [comment]
@juancarlospaco This is definitely still on my list among other python projects.
I am going to have the focus to attend to further development in second half of June.

**Comment by juancarlospaco** [comment]
:+1:

**Comment by pykong** [comment]
@juancarlospaco I am sorry I can not find the time to fix it at the moment.
Also I am not using python/peewee as extensively as in the past, hence this moved down my priority.

How could we proceed? Either we close it, or leave it open for someone else to takeover.

**Comment by juancarlospaco** [comment]
Leave it open for someone else to takeover. We welcome Pull Requests!.

No problem, it happens, thats the point of open source anyways, anyone can contribute...

**Comment by pykong** [comment]
Thanks for your understanding. Keep up the good work at this cool little project.

**Comment by dexax** [comment]
> I'm getting `'EnumField' object has no attribute 'model_class'` when trying to select from a (Sqlite) database with an enum field. It arises from [here](https://github.com/juancarlospaco/peewee-extra-fields/blob/master/peewee_extra_fields/__init__.py#L1033). It doesn't look like this will address it though, so it's a separate issue I think.

It's undepend from the db_driver, the problem is that , this should be `getattr(self,'enum')`. I don't get why this reference to the model on which this field descriptor is attached.

**Comment by dexax** [comment]
Another thing is that this implementation should check if provided Enum is subclass of the IntEnum not just Enum, becase we cannot be sure that the Enum value will be Integer when we take it's value.

**Comment by juancarlospaco** [comment]
Contributions via Pull Requests welcome :grey_exclamation:

**Pull request closed without merging**
